# alembic/versions/xxxx_baseline_current_schema.py
"""baseline_current_schema

Revision ID: <auto-generated>
Revises:
Create Date: <auto-generated>
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "c2d68761ce0f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Events table with recurrence support
    op.create_table(
        "events",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("start_time", sa.Text(), nullable=False),
        sa.Column("end_time", sa.Text()),
        sa.Column("location", sa.Text()),
        sa.Column("category", sa.Text(), server_default="general"),
        sa.Column("is_recurring", sa.Integer(), server_default="0"),
        sa.Column("recurrence_type", sa.Text()),
        sa.Column("recurrence_days", sa.Text()),
        sa.Column("recurrence_end_date", sa.Text()),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP")
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP")
        ),
        sa.Column("order_index", sa.Integer(), server_default="0"),
    )
    op.create_index("idx_events_start_time", "events", ["start_time"])
    op.create_index("idx_events_category", "events", ["category"])

    # Generic Key-Value Store
    op.create_table(
        "short_term_memory",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("key", sa.Text(), unique=True, nullable=False),
        sa.Column("value", sa.Text()),
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP")
        ),
    )

    # User Facts
    op.create_table(
        "user_facts",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("fact", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), server_default="general"),
        sa.Column("confidence", sa.Float(), server_default="1.0"),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP")
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("TRUE")),
    )
    op.create_index("idx_user_facts_category", "user_facts", ["category"])

    # Notes
    op.create_table(
        "notes",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP")
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP")
        ),
    )

    # Chat Threads
    op.create_table(
        "chat_threads",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("title", sa.Text()),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP")
        ),
        sa.Column(
            "last_message_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )

    # Chat Messages
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("thread_id", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP")
        ),
        sa.ForeignKeyConstraint(["thread_id"], ["chat_threads.id"], ondelete="CASCADE"),
    )
    op.create_index("idx_chat_messages_thread_id", "chat_messages", ["thread_id"])
    op.create_index("idx_chat_messages_timestamp", "chat_messages", ["timestamp"])

    # Reminders
    op.create_table(
        "reminders",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("due_time", sa.Text(), nullable=False),
        sa.Column("priority", sa.Text(), server_default="medium"),
        sa.Column("completed", sa.Boolean(), server_default=sa.text("FALSE")),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP")
        ),
    )
    op.create_index("idx_reminders_due_time", "reminders", ["due_time"])
    op.create_index("idx_reminders_completed", "reminders", ["completed"])

    # To-Do Items
    op.create_table(
        "todos",
        sa.Column("id", sa.Text(), primary_key=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("priority", sa.Text(), server_default="medium"),
        sa.Column("completed", sa.Boolean(), server_default=sa.text("FALSE")),
        sa.Column("due_date", sa.Text()),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP")
        ),
        sa.Column("order_index", sa.Integer(), server_default="0"),
    )
    op.create_index("idx_todos_due_date", "todos", ["due_date"])
    op.create_index("idx_todos_completed", "todos", ["completed"])

    # User Profile
    op.create_table(
        "user_profile",
        sa.Column("key", sa.Text(), primary_key=True),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP")
        ),
    )


def downgrade() -> None:
    op.drop_table("user_profile")
    op.drop_table("todos")
    op.drop_table("reminders")
    op.drop_table("chat_messages")
    op.drop_table("chat_threads")
    op.drop_table("notes")
    op.drop_table("user_facts")
    op.drop_table("short_term_memory")
    op.drop_table("events")
